# Generated by Django 4.2.5 on 2023-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reading_history',
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.FileField(upload_to='book_collection/'),
        ),
    ]
