# Generated by Django 4.2.5 on 2023-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_api', '0003_alter_category_options_rename_book_title_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='ALL', max_length=30, unique=True),
        ),
    ]
